#!/usr/bin/env python3
"""Write a hash-pinned requirements file for the verification-only reference tools.

Standard library only. For every `name==version` line in the input it reads
the PyPI JSON API (https://pypi.org/pypi/<name>/<version>/json) and records
the SHA-256 of every wheel pip can select on CPython 3.12 for Linux
x86_64/aarch64 (manylinux), macOS (arm64/x86_64/universal2) and Windows amd64,
plus pure-Python wheels. Source distributions are excluded, so installs are
binary-only and never build code.

Usage: pin_requirements.py requirements-reference.in requirements-reference.txt
Then:  python3.12 -m pip install --require-hashes --only-binary :all: \
           -r requirements-reference.txt
"""

import json
import re
import sys
import urllib.request

PURE = ("-py3-none-any.whl", "-py2.py3-none-any.whl")
ABI = re.compile(r"-(cp312-cp312|cp3\d+-abi3|py3-none)-")
ARCH = ("x86_64", "aarch64", "arm64", "universal2", "win_amd64")


def wanted(filename):
    if not filename.endswith(".whl"):
        return False
    if filename.endswith(PURE):
        return True
    if not ABI.search(filename) or "musllinux" in filename:
        return False
    return any(arch in filename for arch in ARCH)


def main():
    source, target = sys.argv[1], sys.argv[2]
    out = [
        "# GENERATED by tools/embedding/pin_requirements.py from requirements-reference.in.",
        "# Verification-only tools (reference_e5.py, tokenizer_parity.py); never shipped.",
        "# Install: python3.12 -m pip install --require-hashes --only-binary :all: \\",
        "#            -r tools/embedding/requirements-reference.txt",
        "",
    ]
    for line in open(source, encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        name, version = line.split("==")
        url = f"https://pypi.org/pypi/{name}/{version}/json"
        with urllib.request.urlopen(url, timeout=60) as r:
            meta = json.load(r)
        hashes = sorted(
            {f["digests"]["sha256"] for f in meta["urls"] if wanted(f["filename"])}
        )
        if not hashes:
            sys.exit(f"pin_requirements: no matching wheel for {name}=={version}")
        out.append(f"{name}=={version} \\")
        out.extend(f"    --hash=sha256:{h} \\" for h in hashes[:-1])
        out.append(f"    --hash=sha256:{hashes[-1]}")
    with open(target, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
