use std::fmt;

use nagi_localization::MessageId;

pub const NOTIFICATION_MODEL_VERSION: u16 = 1;
pub const NOTIFICATION_STORE_SCHEMA_VERSION: u16 = 1;
pub const MAX_NOTIFICATION_ID_BYTES: usize = 16;
pub const MAX_CONTENT_BYTES: usize = 8 * 1024;
pub const MAX_NOTIFICATION_BYTES: usize = 16 * 1024;
pub const MAX_LOCALIZED_ARGUMENTS: usize = 16;
pub const MAX_ACTIONS: usize = 8;
pub const MAX_ACTION_PARAMETERS: usize = 16;
pub const MAX_GROUPING_KEY_BYTES: usize = 128;
pub const MAX_SAFE_REFERENCE_BYTES: usize = 96;
pub const MAX_CLEANUP_BATCH: usize = 256;
pub const DIAGNOSTIC_WINDOW_MILLIS: u64 = 1_000;
pub const MAX_DIAGNOSTIC_EVENTS_PER_WINDOW: u32 = 128;

/// Opaque, stable ID generated by an injected ID source.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct NotificationId([u8; MAX_NOTIFICATION_ID_BYTES]);

impl NotificationId {
    pub fn new(bytes: [u8; MAX_NOTIFICATION_ID_BYTES]) -> Result<Self, ValidationError> {
        if bytes.iter().all(|byte| *byte == 0) {
            return Err(ValidationError::InvalidNotificationId);
        }
        Ok(Self(bytes))
    }

    pub const fn as_bytes(&self) -> &[u8; MAX_NOTIFICATION_ID_BYTES] {
        &self.0
    }
}

/// Monotonic milliseconds from the injected clock.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct Timestamp(pub u64);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Priority {
    Low,
    Normal,
    High,
    Urgent,
}

impl Priority {
    pub const fn rank(self) -> u8 {
        match self {
            Self::Low => 0,
            Self::Normal => 1,
            Self::High => 2,
            Self::Urgent => 3,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Severity {
    Informational,
    Success,
    Warning,
    Error,
    Critical,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum Sensitivity {
    Public,
    Personal,
    Sensitive,
    Secret,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ArgumentValue {
    Text(String),
    Signed(i64),
    Unsigned(u64),
    Boolean(bool),
    Redacted,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LocalizedArgument {
    pub(crate) name: String,
    pub(crate) value: ArgumentValue,
    pub(crate) sensitivity: Sensitivity,
}

impl LocalizedArgument {
    pub fn new(
        name: impl Into<String>,
        value: ArgumentValue,
        sensitivity: Sensitivity,
    ) -> Result<Self, ValidationError> {
        let name = name.into();
        if !valid_argument_name(&name) {
            return Err(ValidationError::InvalidArgumentName);
        }
        if value_size(&value) > MAX_CONTENT_BYTES {
            return Err(ValidationError::ContentTooLarge);
        }
        Ok(Self {
            name,
            value,
            sensitivity,
        })
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    pub fn value(&self) -> &ArgumentValue {
        &self.value
    }

    pub const fn sensitivity(&self) -> Sensitivity {
        self.sensitivity
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LocalizedMessage {
    pub(crate) message_id: MessageId,
    pub(crate) arguments: Vec<LocalizedArgument>,
}

impl LocalizedMessage {
    pub fn new(
        message_id: MessageId,
        arguments: Vec<LocalizedArgument>,
    ) -> Result<Self, ValidationError> {
        if arguments.len() > MAX_LOCALIZED_ARGUMENTS {
            return Err(ValidationError::TooManyArguments);
        }
        let mut names = std::collections::BTreeSet::new();
        let total = arguments
            .iter()
            .try_fold(message_id.as_str().len(), |size, arg| {
                if !names.insert(arg.name.clone()) {
                    return Err(ValidationError::DuplicateArgument);
                }
                size.checked_add(arg.name.len())
                    .and_then(|size| size.checked_add(value_size(&arg.value)))
                    .ok_or(ValidationError::ContentTooLarge)
            })?;
        if total > MAX_CONTENT_BYTES {
            return Err(ValidationError::ContentTooLarge);
        }
        Ok(Self {
            message_id,
            arguments,
        })
    }

    pub fn message_id(&self) -> &MessageId {
        &self.message_id
    }

    pub fn arguments(&self) -> &[LocalizedArgument] {
        &self.arguments
    }

    pub fn encoded_size(&self) -> usize {
        self.message_id.as_str().len()
            + self
                .arguments
                .iter()
                .map(|argument| argument.name.len() + value_size(&argument.value))
                .sum::<usize>()
    }
}

/// User-facing content is either a shared localization reference or explicitly
/// classified user text. `Redacted` is safe to persist and is resolved by the
/// injected localization adapter for the selected locale.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum NotificationContent {
    Localized(LocalizedMessage),
    UserText {
        text: String,
        sensitivity: Sensitivity,
    },
    Redacted,
}

impl NotificationContent {
    pub fn user_text(
        text: impl Into<String>,
        sensitivity: Sensitivity,
    ) -> Result<Self, ValidationError> {
        let text = text.into();
        if text.trim().is_empty() {
            return Err(ValidationError::EmptyContent);
        }
        if text.len() > MAX_CONTENT_BYTES {
            return Err(ValidationError::ContentTooLarge);
        }
        Ok(Self::UserText { text, sensitivity })
    }

    pub fn localized(message: LocalizedMessage) -> Self {
        Self::Localized(message)
    }

    pub fn sensitivity(&self) -> Sensitivity {
        match self {
            Self::Localized(message) => message
                .arguments()
                .iter()
                .map(LocalizedArgument::sensitivity)
                .max()
                .unwrap_or(Sensitivity::Public),
            Self::UserText { sensitivity, .. } => *sensitivity,
            Self::Redacted => Sensitivity::Public,
        }
    }

    pub fn encoded_size(&self) -> usize {
        match self {
            Self::Localized(message) => message.encoded_size(),
            Self::UserText { text, .. } => text.len(),
            Self::Redacted => 0,
        }
    }
}

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct GroupingKey(String);

impl GroupingKey {
    pub fn new(value: impl Into<String>) -> Result<Self, ValidationError> {
        let value = value.into();
        if value.trim().is_empty()
            || value.len() > MAX_GROUPING_KEY_BYTES
            || value.chars().any(char::is_control)
        {
            return Err(ValidationError::InvalidGroupingKey);
        }
        Ok(Self(value))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ActionId(String);

impl ActionId {
    pub fn new(value: impl Into<String>) -> Result<Self, ValidationError> {
        let value = value.into();
        if !valid_action_id(&value) {
            return Err(ValidationError::InvalidActionId);
        }
        Ok(Self(value))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ActionValue {
    Text(String),
    Signed(i64),
    Unsigned(u64),
    Boolean(bool),
    Redacted,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ActionParameter {
    pub(crate) name: String,
    pub(crate) value: ActionValue,
    pub(crate) sensitivity: Sensitivity,
}

impl ActionParameter {
    pub fn new(
        name: impl Into<String>,
        value: ActionValue,
        sensitivity: Sensitivity,
    ) -> Result<Self, ValidationError> {
        let name = name.into();
        if !valid_argument_name(&name) {
            return Err(ValidationError::InvalidArgumentName);
        }
        if action_value_size(&value) > MAX_CONTENT_BYTES {
            return Err(ValidationError::ContentTooLarge);
        }
        Ok(Self {
            name,
            value,
            sensitivity,
        })
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    pub fn value(&self) -> &ActionValue {
        &self.value
    }

    pub const fn sensitivity(&self) -> Sensitivity {
        self.sensitivity
    }
}

/// Data-only descriptor. It cannot contain a closure, executable code, grant,
/// token, or capability handle.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ActionDescriptor {
    pub(crate) id: ActionId,
    pub(crate) label: Option<LocalizedMessage>,
    pub(crate) parameters: Vec<ActionParameter>,
}

impl ActionDescriptor {
    pub fn new(
        id: ActionId,
        label: Option<LocalizedMessage>,
        parameters: Vec<ActionParameter>,
    ) -> Result<Self, ValidationError> {
        if parameters.len() > MAX_ACTION_PARAMETERS {
            return Err(ValidationError::TooManyActionParameters);
        }
        if label
            .as_ref()
            .is_some_and(|label| label.encoded_size() > MAX_CONTENT_BYTES)
        {
            return Err(ValidationError::ContentTooLarge);
        }
        let mut names = std::collections::BTreeSet::new();
        if parameters
            .iter()
            .any(|parameter| !names.insert(parameter.name.clone()))
        {
            return Err(ValidationError::DuplicateArgument);
        }
        if parameters
            .iter()
            .map(|parameter| parameter.name.len() + action_value_size(&parameter.value))
            .sum::<usize>()
            > MAX_CONTENT_BYTES
        {
            return Err(ValidationError::ContentTooLarge);
        }
        Ok(Self {
            id,
            label,
            parameters,
        })
    }

    pub fn id(&self) -> &ActionId {
        &self.id
    }

    pub fn label(&self) -> Option<&LocalizedMessage> {
        self.label.as_ref()
    }

    pub fn parameters(&self) -> &[ActionParameter] {
        &self.parameters
    }

    pub fn encoded_size(&self) -> usize {
        self.id.as_str().len()
            + self
                .label
                .as_ref()
                .map_or(0, LocalizedMessage::encoded_size)
            + self
                .parameters
                .iter()
                .map(|parameter| parameter.name.len() + action_value_size(&parameter.value))
                .sum::<usize>()
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SourceKind {
    Application,
    SystemService,
}

/// Safe reference minted by the source-identity adapter for diagnostics.
/// It is attribution metadata and never authenticates a caller.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct SafeSourceReference(String);

impl SafeSourceReference {
    pub fn new(value: impl Into<String>) -> Result<Self, ValidationError> {
        let value = value.into();
        if value.is_empty()
            || value.len() > MAX_SAFE_REFERENCE_BYTES
            || !value.bytes().all(|byte| {
                byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'-' | b'_' | b':')
            })
        {
            return Err(ValidationError::InvalidSafeReference);
        }
        Ok(Self(value))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Profile-scoped correlation generated by the identity adapter. This is not
/// a ProfileId and must not be used for authorization or persistence routing.
/// The all-zero value is reserved for aggregate service-level diagnostics.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SafeProfileCorrelation([u8; 16]);

impl SafeProfileCorrelation {
    pub const fn new(bytes: [u8; 16]) -> Self {
        Self(bytes)
    }

    pub const fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }
}

/// Result of authenticating an existing application or service identity.
/// The generic identity stays owned by its canonical workstream.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct VerifiedSource<S> {
    pub(crate) identity: S,
    pub(crate) kind: SourceKind,
    pub(crate) attribution: NotificationContent,
    pub(crate) diagnostic_reference: SafeSourceReference,
}

impl<S> VerifiedSource<S> {
    pub fn from_identity_adapter(
        identity: S,
        kind: SourceKind,
        attribution: NotificationContent,
        diagnostic_reference: SafeSourceReference,
    ) -> Self {
        Self {
            identity,
            kind,
            attribution,
            diagnostic_reference,
        }
    }

    pub fn identity(&self) -> &S {
        &self.identity
    }

    pub const fn kind(&self) -> SourceKind {
        self.kind
    }

    pub fn attribution(&self) -> &NotificationContent {
        &self.attribution
    }

    pub fn diagnostic_reference(&self) -> &SafeSourceReference {
        &self.diagnostic_reference
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ReadState {
    Unread,
    Read,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum LifecycleState {
    Active,
    Acknowledged,
    Dismissed,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DeliveryState {
    Immediate,
    Deferred { until: Timestamp },
    Suppressed { retain_until: Timestamp },
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PolicyDecision {
    Permit,
    DeferUntil(Timestamp),
    SuppressWithRetention(Timestamp),
    Reject(PolicyReason),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PolicyFailureMode {
    Reject,
    DeferForMillis(u64),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PolicyReason {
    QuietMode,
    FocusMode,
    RateLimited,
    UserPolicy,
    InvalidDecision,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum NotificationOperation {
    Publish,
    List,
    Read,
    MarkRead,
    Acknowledge,
    Dismiss,
    Export,
    ResolveAction,
    CleanupExpired,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CapabilityDecision {
    pub allowed: bool,
    pub may_view_sensitive: bool,
}

impl CapabilityDecision {
    pub const fn deny() -> Self {
        Self {
            allowed: false,
            may_view_sensitive: false,
        }
    }

    pub const fn allow() -> Self {
        Self {
            allowed: true,
            may_view_sensitive: false,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RedactionBoundary {
    Persistence,
    Query,
    Ui,
    Diagnostics,
    Export,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ActionAvailability {
    Available,
    Unavailable,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum NotificationEventCode {
    Published,
    PublishRejected,
    PolicyPermitted,
    PolicyDeferred,
    PolicySuppressed,
    QueryDenied,
    CapabilityDenied,
    ReadChanged,
    Acknowledged,
    Dismissed,
    Expired,
    Evicted,
    CapacityRejected,
    Redacted,
    StoreRecovered,
    MigrationApplied,
    StoreFailure,
    ActionAllowed,
    ActionDenied,
    SourceUnavailable,
    DiagnosticsSinkFailure,
    DiagnosticsRateLimited,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum NotificationReasonCode {
    InvalidInput,
    PermissionDenied,
    SourceRejected,
    PolicyRejected,
    PolicyUnavailable,
    CapacityExceeded,
    PersistenceUnavailable,
    PersistenceConflict,
    CorruptState,
    UnsupportedSchema,
    MigrationFailed,
    GenerationExhausted,
    ActionUnavailable,
    Expired,
    ReadOnlyRecovery,
    DiagnosticsUnavailable,
}

/// Diagnostics deliberately contain no title, body, localized argument, or
/// action parameter fields.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NotificationDiagnosticEvent {
    pub code: NotificationEventCode,
    pub notification_id: Option<NotificationId>,
    pub source_reference: Option<SafeSourceReference>,
    pub profile_correlation: SafeProfileCorrelation,
    pub reason: Option<NotificationReasonCode>,
    pub count: u32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ValidationError {
    InvalidNotificationId,
    InvalidArgumentName,
    InvalidActionId,
    InvalidGroupingKey,
    InvalidSafeReference,
    EmptyContent,
    ContentTooLarge,
    TooManyArguments,
    TooManyActionParameters,
    DuplicateArgument,
    TooManyActions,
    InvalidExpiry,
    InvalidQueryLimit,
}

impl fmt::Display for ValidationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::InvalidNotificationId => "notification id must be non-zero",
            Self::InvalidArgumentName => "invalid localized argument name",
            Self::InvalidActionId => "invalid action id",
            Self::InvalidGroupingKey => "invalid grouping key",
            Self::InvalidSafeReference => "invalid safe reference",
            Self::EmptyContent => "notification content is empty",
            Self::ContentTooLarge => "notification content exceeds its byte limit",
            Self::TooManyArguments => "too many localized arguments",
            Self::TooManyActionParameters => "too many action parameters",
            Self::DuplicateArgument => "duplicate argument name",
            Self::TooManyActions => "too many action descriptors",
            Self::InvalidExpiry => "expiry must be later than creation time",
            Self::InvalidQueryLimit => "query limit is outside the configured bound",
        })
    }
}

impl std::error::Error for ValidationError {}

fn valid_argument_name(value: &str) -> bool {
    !value.is_empty()
        && value.as_bytes()[0].is_ascii_alphabetic()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
}

fn valid_action_id(value: &str) -> bool {
    if value.is_empty() || value.len() > 128 || value.starts_with('.') || value.ends_with('.') {
        return false;
    }
    let mut segments = value.split('.');
    let mut count = 0;
    for segment in &mut segments {
        count += 1;
        if segment.is_empty()
            || !segment.bytes().all(|byte| {
                byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'-' | b'_')
            })
        {
            return false;
        }
    }
    count >= 2
}

fn value_size(value: &ArgumentValue) -> usize {
    match value {
        ArgumentValue::Text(text) => text.len(),
        ArgumentValue::Signed(_) | ArgumentValue::Unsigned(_) => 8,
        ArgumentValue::Boolean(_) => 1,
        ArgumentValue::Redacted => 0,
    }
}

fn action_value_size(value: &ActionValue) -> usize {
    match value {
        ActionValue::Text(text) => text.len(),
        ActionValue::Signed(_) | ActionValue::Unsigned(_) => 8,
        ActionValue::Boolean(_) => 1,
        ActionValue::Redacted => 0,
    }
}
