[package]
name = "nagi-kernel"
version = "0.1.0"
edition = "2021"
publish = false
autobins = false

[features]
default = []
m18-browser-threads = ["nagi-abi/m18-browser-threads"]
m18-browser-memory = ["m18-browser-threads"]
m20-llama-memory = []
m25-whisper-memory = []

[lib]
name = "nagi_kernel"
path = "src/lib.rs"

[[bin]]
name = "nagi-kernel"
path = "src/main.rs"
test = false
bench = false

[dependencies]
nagi-abi = { path = "../crates/nagi-abi" }
nagi-bootinfo = { path = "../crates/nagi-bootinfo" }
