[workspace]
members = ["."]
resolver = "2"

[package]
name = "nagi-notes"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "nagi-notes-preview"
path = "src/bin/preview.rs"

[dependencies]
nagi-model = { path = "../../crates/nagi-model" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("nagi"))'] }
