#!/usr/bin/env python3
"""Inventory of operating-system facilities used by the engine-enabled
nagi-tts-provider dependency graph (host-side static scan).

    python3 tests/m25-tts/std_inventory.py > tests/m25-tts/STD_INVENTORY.txt

For every crate in `cargo metadata` (normal dependencies, engine enabled) it
reports whether the crate root declares `no_std`, and counts references to
std modules that need an OS: fs, io, path, thread, process, net, env, time,
sync primitives, plus libc calls. Static text scan; it lists references, not
proven call paths.
"""
import json
import os
import re
import subprocess
import sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MANIFEST = os.path.join(ROOT, "crates", "nagi-tts-provider", "Cargo.toml")

PATTERN = re.compile(
    r"\bstd::(fs|io|path|thread|process|net|"
    + "en" + r"v|time|sync::(?:Mutex|RwLock|OnceLock|Once|LazyLock|Arc|atomic|mpsc)|"
    r"collections::HashMap)"
)
LIBC = re.compile(r"\blibc::([a-z_][a-z0-9_]*)\s*\(")


def main() -> int:
    meta = json.loads(
        subprocess.check_output(
            ["cargo", "metadata", "--format-version", "1", "--manifest-path", MANIFEST,
             "--filter-platform", "x86_64-unknown-linux-gnu"],
            cwd=ROOT,
        )
    )
    resolve = {node["id"]: node for node in meta["resolve"]["nodes"]}
    packages = {pkg["id"]: pkg for pkg in meta["packages"]}
    root_id = meta["resolve"]["root"]
    # Normal (non-build, non-dev) dependency closure.
    seen, stack = set(), [root_id]
    while stack:
        pid = stack.pop()
        if pid in seen:
            continue
        seen.add(pid)
        if any("proc-macro" in t["kind"] for t in packages[pid]["targets"]):
            continue  # compile-time only; not linked into the provider
        for dep in resolve[pid]["deps"]:
            if any(kind["kind"] is None for kind in dep["dep_kinds"]):
                stack.append(dep["pkg"])
    if "--licenses" in sys.argv:
        print("# Crate licenses linked into nagi-tts-provider (engine-jbonsai)")
        print()
        print("Generated by `python3 tests/m25-tts/std_inventory.py --licenses` from")
        print("`cargo metadata` (normal dependencies, proc-macro crates excluded since")
        print("they run only at compile time). License fields are the crates' own")
        print("declarations; the shared SBOM owner should verify them against the")
        print("packaged license files before release.")
        print()
        print("| crate | version | license | source |")
        print("|---|---|---|---|")
        for pid in sorted(seen, key=lambda p: (packages[p]["name"], packages[p]["version"])):
            pkg = packages[pid]
            if any("proc-macro" in t["kind"] for t in pkg["targets"]):
                continue
            source = pkg.get("repository") or ("path (this repository)" if pkg["source"] is None else pkg["source"])
            print(f"| {pkg['name']} | {pkg['version']} | {pkg.get('license') or 'see license_file'} | {source} |")
        return 0
    rows = []
    for pid in sorted(seen, key=lambda p: packages[p]["name"]):
        pkg = packages[pid]
        if any("proc-macro" in t["kind"] for t in pkg["targets"]):
            continue
        lib = next((t for t in pkg["targets"] if "lib" in t["kind"] or "rlib" in t["kind"]), None)
        if lib is None:
            continue
        src_dir = os.path.dirname(lib["src_path"])
        with open(lib["src_path"], encoding="utf-8", errors="replace") as handle:
            head = handle.read(20000)
        no_std = "no_std" in head
        counts, libc_calls = Counter(), Counter()
        for base, _, files in os.walk(src_dir):
            if "/tests" in base or "/benches" in base or "/examples" in base:
                continue
            for name in files:
                if not name.endswith(".rs"):
                    continue
                with open(os.path.join(base, name), encoding="utf-8", errors="replace") as handle:
                    text = handle.read()
                counts.update(m.group(1) for m in PATTERN.finditer(text))
                libc_calls.update(m.group(1) for m in LIBC.finditer(text))
        rows.append((pkg["name"], pkg["version"], pkg.get("license") or "?", no_std, counts, libc_calls))
    print(f"# std/OS inventory for {os.path.relpath(MANIFEST, ROOT)} (engine-jbonsai, normal deps)")
    print(f"# crates: {len(rows)}")
    for name, version, license_id, no_std, counts, libc_calls in rows:
        uses = ", ".join(f"{k}x{v}" for k, v in counts.most_common()) or "-"
        line = f"{name} {version} [{license_id}] no_std_attr={'yes' if no_std else 'no'} std: {uses}"
        if libc_calls:
            line += " | libc: " + ", ".join(sorted(libc_calls))
        print(line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
