[package]
name = "nagi-ai"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
nagi-model = { path = "../../crates/nagi-model" }
nagi-model-manager = { path = "../../user/nagi-model-manager" }
serde = { version = "=1.0.229", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "=1.0.151", default-features = false, features = ["alloc"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("nagi"))'] }
