set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

get_filename_component(NAGI_REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(CMAKE_C_COMPILER "${NAGI_REPOSITORY_ROOT}/tools/nagi-target-cc.sh")
set(CMAKE_CXX_COMPILER "${NAGI_REPOSITORY_ROOT}/tools/nagi-target-cc.sh")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(DEFINED ENV{NAGI_LLVM_AR})
  set(CMAKE_AR "$ENV{NAGI_LLVM_AR}")
endif()
if(DEFINED ENV{NAGI_LLVM_RANLIB})
  set(CMAKE_RANLIB "$ENV{NAGI_LLVM_RANLIB}")
endif()
