[package]
name = "nagi-calendar-core"
version = "0.2.0"
edition = "2021"
publish = false

[workspace]
resolver = "2"

[dependencies]
nagi-model = { git = "https://github.com/RT-NISH/NagiOS.git", rev = "cd871f905bd06ef406ccaa9f80c484f19158209f", version = "=0.1.0" }

[lints.rust]
unsafe_code = "forbid"
